# Generated by Django 6.0.6 on 2026-08-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_creatorgroup_creatorgroupmember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatorGroup',
            new_name='PublishGroup',
        ),
        migrations.RenameModel(
            old_name='CreatorGroupMember',
            new_name='PublishGroupMember',
        ),
    ]
