# Generated by Django 6.0.6 on 2026-08-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_creatorgroup_publishgroup_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishGroup',
            new_name='CreatorGroup',
        ),
        migrations.RenameModel(
            old_name='PublishGroupMember',
            new_name='CreatorGroupMember',
        ),
    ]
