# Generated by Django 6.0.6 on 2026-08-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_publishgroup_creatorgroup_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creatorgroupmember',
            name='unique_group_member',
        ),
        migrations.RemoveField(
            model_name='creatorgroupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='creatorgroupmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='CreatorGroup',
        ),
        migrations.DeleteModel(
            name='CreatorGroupMember',
        ),
    ]
