# Generated by Django 6.0.6 on 2026-07-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='novels', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='novels', to='catalog.tag'),
        ),
    ]
