# Generated by Django 6.0.6 on 2026-07-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_creator_alter_genre_options_alter_novel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='illustrated_novels', to='catalog.creator'),
        ),
        migrations.AddField(
            model_name='novel',
            name='authors',
            field=models.ManyToManyField(related_name='written_novels', to='catalog.creator'),
        ),
    ]
