# Generated by Django 6.0.6 on 2026-07-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_novel_artists_novel_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('number', models.DecimalField(decimal_places=2, max_digits=6)),
                ('content', models.TextField()),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalog.novel')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
