# Generated by Django 6.0.6 on 2026-07-05 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
