# Generated by Django 6.0.6 on 2026-08-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_teammembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.team'),
        ),
    ]
