# Generated by Django 6.0.6 on 2026-08-31 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_teammembership_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='novel',
            name='submission_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='NovelSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=20)),
                ('moderator_notes', models.TextField(blank=True, help_text='Provide feedback to the submitter (e.g., reason for rejection or needed edits).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_request', to='catalog.novel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_novels', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novel_submissions', to='catalog.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
