# Generated by Django 6.0.6 on 2026-08-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_team_options_novel_submission_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='submission_status',
        ),
        migrations.AddField(
            model_name='novel',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='pending', max_length=10, null=True),
        ),
    ]
