# Generated by Django 6.0.6 on 2026-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_novel_submission_status_novel_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=10, null=True),
        ),
    ]
